spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch_processing
    username: root
    password: root
  sql:
    init:
      mode: always
  batch:
    jdbc:
      initialize-schema: always


# bath related configurations





